name: "Update"
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6
        with:
          token: '${{ secrets.UPDATE_GITHUB_TOKEN }}'
          fetch-depth: 0
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # ratchet:cachix/install-nix-action@v31
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # ratchet:cachix/cachix-action@v17
        with:
          name: ardupilot
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Configure git user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Update flake
        run: |
          nix --version
          nix flake update --commit-lock-file
          git push
